name: shop_app
description: A new Shop app project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # For Architecture
  flutter_hooks: ^0.18.2+1
  hooks_riverpod: ^1.0.3
  state_notifier: ^0.7.2+1

  # For Navigation
  auto_route: ^3.2.4

  # For Networking
  dio: ^4.0.4
  connectivity_plus: ^2.2.1

  # For Auth
  flutter_secure_storage: ^5.0.2

  # For Model
  equatable: ^2.0.3
  freezed_annotation: ^1.1.0

  # For Local data
  shared_preferences: ^2.0.13

  # For env
  flutter_dotenv: ^5.0.2
  flutter_flavor: ^3.0.3

  # For utils
  validators: ^3.0.0

  # For date time
  intl: ^0.17.0

  # For UIs
  device_preview: ^1.0.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  shimmer: ^2.0.0
  intro_views_flutter: ^3.2.0
  page_indicator: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7

  # For Analyzer
  flutter_lints: ^1.0.4

  # For Assets
  flutter_gen_runner: ^4.1.5

  # For Navigation
  auto_route_generator: ^3.2.3

  # For Model
  freezed: ^1.1.1

  # For Testing
  mocktail: any
  mocktail_image_network: any

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/gifs/
    - assets/icons/
    - assets/images/
    - assets/mocks/avatars/
    - assets/mocks/img_brand/
    - assets/mocks/img_camera/
    - assets/mocks/img_category_man/
    - assets/mocks/img_item/
    - assets/mocks/img_promo/


  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 200
    - family: Popins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: Berlin
      fonts:
        - asset: assets/fonts/BRLNSDB.TTF
          weight: 700
    - family: Gotik
      fonts:
        - asset: assets/fonts/GOTHIC.TTF
          weight: 400
        - asset: assets/fonts/GOTHICB.TTF
          weight: 600

flutter_gen:
  output: lib/presentation/widgets/stless/assets_gen/
  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
  class_name: L10n
  main_locale: en
  arb_dir: lib/presentation/l10n/message
  output_dir: lib/presentation/l10n
